language: go

go:
  - '1.12'
  - '1.13'
  - tip

git:
  depth: 1

env:
  matrix:
  - GO111MODULE=on
  global:
    secure: 1GvewNqlQugtK8EhENu2IxL1WanpbrlKgIUyzo3WMBMrJqZNb8q1j2xAxGeEoDMjQmwAreabCGjUrX4QeIXwzHhIAZSUO70P8vyszN5LW+bSAWAhXdm2siKFybeEEvEDOeeh14Ruv1Wuw/3l9jlvYh1mdpGIG4twcZQ3f1Ei6VS8rx5iLEYp5R4b4MFyx0FN3JeBPawo57Cz6hvN8NO+goDL+SNflOa7PhRytVSlNoNRxXr70rj1T5MVfJa3oUtyQJgiDYyi4LWWHZ7+lpE1UzIEWxOvtySeZgM30+EwK/xdCoIwjqjr9xhgJ9Oxa2UwE0PKpJuC/njj6TVZWLDcBN6NxfeIIJZLaRTGKjyDcbDhc2CGC35qT5E7OU64zh881MxCr0TKAebr3fawwfxuk94H00GYXaaQx01C5+y7qW/Zvu5b7kDP0vCzoqk6eNNjF6AoHibEmzE/KjHDJ2Uu0GEX4H+UnAx5UiIocxa+66xlK8h3BQG10eyBPd8aWm43BgHshG9VLL5oGlKc48dOqI9oj/5BbFiMmxKTdvRdXbXTa0D6BT6BREL6h65nLj07LN8w47BDggwFUuQBpZryGHJ6VPMYhpjYI7BvB+9OvvrnYv8ta3cfzXe0Xfh3N7dRYZkuEiAwUWOdoL401gqBDe9yPxhM3lbfXPS39K1/Nm8=

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - test $TRAVIS_GO_VERSION != "tip" && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      os: linux
      condition: "$TRAVIS_GO_VERSION != tip"
